version: '2.1'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - user-api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5

  app:
    container_name: user-api
    build: .
    ports:
      - 9090:9090
      - 9092:9092
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - user-api

volumes:
  database_postgres:

networks:
  user-api:
    driver:
       bridge