version: '2.1'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - '5555:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - user-api-test

  app_test:
    container_name: user-api-test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - user-api-test

volumes:
  database_postgres_test:

networks:
  user-api-test:
    driver:
      bridge